import React from 'react';


const Dashboard = () => {
    return (
        <>
            <h1>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam luctus lacus a pretium hendrerit. Morbi faucibus, tortor vel venenatis gravida, enim mi laoreet enim, gravida consequat dui augue a odio. Aenean luctus, dolor ut pulvinar mollis, mauris nulla ultricies ante, luctus facilisis risus elit eget dui. Nunc at eros at eros ultricies dignissim. Integer nec urna lobortis, malesuada sapien elementum, aliquet lectus. Aenean in mi augue. Aenean posuere est ut risus sollicitudin tristique. Integer tincidunt, leo id rutrum luctus, nisl mauris consectetur augue, ac sollicitudin nunc nisi in urna. Quisque rutrum feugiat dolor vitae feugiat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin a aliquam urna. Sed a nunc id dolor ullamcorper lobortis. Sed ultrices mauris id massa rutrum, quis posuere leo tempor. Nam viverra ipsum vel fringilla venenatis. Duis non felis turpis.

Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aenean posuere vitae est eget lacinia. Maecenas dictum libero sed pellentesque dapibus. Donec condimentum varius risus, nec hendrerit sem luctus eu. Cras sem ipsum, fermentum tincidunt facilisis vel, efficitur sed dolor. Cras vel justo cursus, rhoncus ex sit amet, vulputate dui. Interdum et malesuada fames ac ante ipsum primis in faucibus.

Donec faucibus pharetra nulla, vel lacinia lectus euismod sed. Sed porta ex neque, vitae tempor leo mattis a. Etiam maximus euismod magna, ut iaculis dui bibendum at. Curabitur tellus nibh, efficitur non est ut, molestie dignissim elit. Curabitur sit amet velit quis dui vulputate pharetra. Aenean est purus, molestie id vulputate et, ultrices vel elit. Donec maximus, risus quis aliquet lacinia, odio urna tincidunt ligula, sit amet pellentesque enim nisl et erat. Donec nisi augue, molestie vel ex efficitur, dapibus hendrerit erat. Integer egestas dui erat, suscipit pulvinar mauris mattis id. Fusce at vulputate tortor. Aenean ac est dui.

Integer ornare semper fringilla. Morbi est tortor, interdum sit amet sapien a, sagittis eleifend enim. Vivamus volutpat enim lacus, eget vehicula nisl dictum vel. Vestibulum orci ex, suscipit non nisl vel, posuere imperdiet orci. Quisque consectetur facilisis velit, at fringilla dui mollis vel. Cras sagittis malesuada est, id laoreet tellus egestas ut. Etiam in feugiat erat, vel congue mauris. Phasellus tortor ligula, ornare eget gravida porttitor, sagittis eget ligula. Mauris iaculis enim non lacus faucibus, eget vehicula erat iaculis.

Proin sollicitudin dignissim nulla, et bibendum mi bibendum pretium. Sed tincidunt cursus nisi eu semper. Curabitur a lorem quis purus tempus imperdiet. Praesent aliquam orci eget urna feugiat interdum. Mauris non sapien eu augue vestibulum volutpat sollicitudin dignissim dolor. Mauris augue nulla, pulvinar eu augue a, varius varius est. Vestibulum nisl nisi, porttitor quis nulla a, luctus tempus felis.

Maecenas pretium augue mattis efficitur pharetra. Curabitur quis risus ut justo porta rhoncus. Nunc sem justo, condimentum nec risus in, ultricies volutpat ipsum. Nunc imperdiet nisl in efficitur scelerisque. Phasellus non tempus turpis, sit amet congue nulla. Integer vel ante nisi. Aenean id risus et mauris volutpat feugiat sit amet vitae velit. Fusce venenatis lobortis magna, sed consequat enim dictum ut. Nam suscipit auctor diam, elementum pellentesque sapien euismod nec. In mollis congue mi, vitae venenatis felis rutrum vel. Duis tristique non quam eget tempor. Praesent vitae tellus viverra, iaculis nunc sed, suscipit lorem. In sit amet purus vestibulum, facilisis orci non, fringilla ipsum. Nam ornare dolor mollis, facilisis dui a, egestas ex. Fusce in lectus id urna blandit euismod. Etiam elementum accumsan congue.

Donec facilisis ex convallis, ultricies nulla quis, pellentesque ipsum. Donec sollicitudin risus aliquam bibendum placerat. Nulla elementum orci quis iaculis condimentum. Maecenas faucibus nibh eu ante placerat iaculis. In hac habitasse platea dictumst. Sed orci enim, commodo sed faucibus sollicitudin, egestas non neque. Phasellus varius egestas risus et efficitur. In in blandit ex. Etiam imperdiet imperdiet mollis. Sed eu pharetra ipsum. Duis nec eros vitae nulla finibus pharetra a eu turpis. Maecenas turpis mauris, lacinia in neque nec, luctus porttitor eros. Vestibulum rutrum a velit eget feugiat. Suspendisse ornare sapien in ultricies aliquet. Donec vel arcu dapibus, suscipit risus id, congue mi.

Aenean quis massa augue. Vivamus ut dui augue. In eget justo egestas, posuere neque ac, eleifend odio. Aenean in eros fringilla lectus convallis elementum. Ut nunc sem, maximus sit amet gravida vel, euismod euismod metus. Pellentesque vehicula at ligula at sagittis. Duis fringilla, diam laoreet tincidunt sollicitudin, leo eros mattis massa, ac accumsan quam purus non urna. Aliquam et nisl nec magna rhoncus sollicitudin. Nunc blandit malesuada metus. Cras ullamcorper purus et imperdiet lobortis. Sed laoreet sollicitudin elit, iaculis interdum dui hendrerit a. Sed aliquet lectus id quam fringilla dignissim. Integer hendrerit urna nec nulla efficitur volutpat. Ut porta mollis nisi, sed bibendum eros suscipit sit amet. Phasellus volutpat magna lectus, eu tempor tortor laoreet sed.

Nullam eu ipsum eget dolor sollicitudin feugiat. Nullam ultricies risus sit amet purus tincidunt imperdiet. Sed dictum arcu eget sodales dignissim. Aliquam ornare blandit enim, id aliquam augue feugiat in. Proin suscipit ex non lobortis molestie. Duis aliquet rhoncus velit, pellentesque ultrices nibh varius a. Maecenas cursus lorem leo, a accumsan tellus maximus sit amet. Suspendisse commodo mattis odio, at imperdiet urna maximus fringilla. Etiam varius pretium dolor, quis porta diam commodo scelerisque. Cras sit amet sodales elit. Duis non nisl a nulla pretium cursus. Vestibulum non finibus nibh. Nunc sagittis mauris dolor, sit amet maximus orci condimentum id.

Donec pretium augue ac euismod congue. Maecenas fringilla ex eu dapibus ultricies. Aenean lacinia felis eget nisi lacinia lacinia. Sed arcu ligula, molestie eget consequat eu, hendrerit vel diam. Integer congue libero vel nibh ultricies placerat. Vivamus placerat erat non suscipit faucibus. Curabitur ut metus at mauris elementum ornare.
            </h1>
        </>
    )

}
export default Dashboard;